// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Tender struct {
	Uid         int64
	Uuid        string
	CreatedAt   int64
	UpdatedAt   int64
	Source      string
	Link        string
	Title       string
	UnixDate    int64
	Categories  string
	Description string
	Guid        string
	JsonVersion string
	Json        string
	Attempt     int64
	Error       string
	PublishAt   int64
	ClosingAt   int64
	Deleted     int64
}
